type_body_length:
    - 500 # warning
  
file_length:
    warning: 800
    error: 1600
  
opt_in_rules:
    - anyobject_protocol
    - array_init
    - closure_end_indentation
    - closure_spacing
    - contains_over_filter_count
    - contains_over_first_not_nil
    - discarded_notification_center_observer
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - fatal_error_message
    - file_name
    - first_where
    - force_unwrapping
    - function_default_parameter_at_end
    - identical_operands
    - implicit_return
    - joined_default_parameter
    - last_where
    - literal_expression_end_indentation
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - private_action
    - private_outlet
    - redundant_type_annotation
    - sorted_imports
    - switch_case_on_newline
    - unused_import
    - unneeded_parentheses_in_closure_argument
    - vertical_whitespace_opening_braces
    - vertical_whitespace_closing_braces

excluded:
  - Pods
  - GudTay/Resources/Generated
  - BetMaster/Extensions
  - BetMaster/MVC/ViewControllers/TestVC/Source
